# Generated by Django 5.2.1 on 2025-06-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='emotion',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='emotion',
            field=models.CharField(choices=[('Joy', 'Joy'), ('Sadness', 'Sadness'), ('Anger', 'Anger'), ('Calm', 'Calm'), ('Surprise', 'Surprise'), ('Love', 'Love')], default='Joy', max_length=50),
            preserve_default=False,
        ),
    ]
