# Generated by Django 5.2.1 on 2025-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0004_alter_diarypage_user_alter_moodentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypage',
            name='tags',
        ),
        migrations.AddField(
            model_name='diarypage',
            name='title',
            field=models.CharField(default='Temporary Title', max_length=100),
            preserve_default=False,
        ),
    ]
